module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.test.ts'],
  moduleFileExtensions: ['ts', 'js'],
  roots: ['<rootDir>/src'],
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'json', 'html'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  collectCoverageFrom: [
    'src/**/*.{ts,js}',
    '!src/**/*.d.ts',
    '!src/__tests__/**',
    '!src/types/**',
    '!src/constants/**',
    '!src/config/**',
    '!src/**/index.ts',
    '!src/app.ts',
    '!src/server.ts',
  ],
  verbose: true,
  testTimeout: 60000,
  maxWorkers: 1,
  globalSetup: '<rootDir>/src/__tests__/setup.ts',
  globalTeardown: '<rootDir>/src/__tests__/teardown.ts',
};
